export const Payments = {
  CREDIT_CARD: {
    id: "method01",
    value: "CREDIT_CARD",
    name: "신용카드",
    color: "#1E90FF",
    subColor: "#E1F5FE",
    icon: "fa-solid fa-credit-card",
  },
  CHECK_CARD: {
    id: "method02",
    value: "CHECK_CARD",
    name: "체크카드",
    color: "#00CED1",
    subColor: "#E0F7FA",
    icon: "fa-solid fa-wallet",
  },
  CASH: {
    id: "method03",
    value: "CASH",
    name: "현금",
    color: "#2ECC71",
    subColor: "#E8F5E9",
    icon: "fa-solid fa-money-bill-wave",
  },
  BANK_TRANSFER: {
    id: "method04",
    value: "TRANSFER",
    name: "계좌이체",
    color: "#9B59B6",
    subColor: "#F3E5F5",
    icon: "fa-solid fa-building-columns",
  },
  EASY_PAY: {
    id: "method05",
    value: "MOBILE",
    name: "간편결제",
    color: "#F39C12",
    subColor: "#FFF3E0",
    icon: "fa-solid fa-mobile-screen-button",
  },
};
